export const FETCH_EMISSIONS_START = 'FETCH_EMISSIONS_START';
export const FETCH_EMISSIONS_SUCCESS = 'FETCH_EMISSIONS_SUCCESS';
export const FETCH_EMISSIONS_FAIL = 'FETCH_EMISSIONS_FAIL';

export const FETCH_POPULATIONS_START = 'FETCH_POPULATIONS_START';
export const FETCH_POPULATIONS_SUCCESS = 'FETCH_POPULATIONS_SUCCESS';
export const FETCH_POPULATIONS_FAIL = 'FETCH_POPULATIONS_FAIL';